// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK3NQJxChbeKDzSlpfAIA2xaohgXjDTV4',
    appId: '1:276263631177:web:ea6e2785370e294492c298',
    messagingSenderId: '276263631177',
    projectId: 'finalyp-580ad',
    authDomain: 'finalyp-580ad.firebaseapp.com',
    storageBucket: 'finalyp-580ad.firebasestorage.app',
    measurementId: 'G-HK0NXVG6YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_rAq0aZmyxqe4Ywo9o_UM4p-IpBMyDJU',
    appId: '1:276263631177:android:9be08cc8e5109fab92c298',
    messagingSenderId: '276263631177',
    projectId: 'finalyp-580ad',
    storageBucket: 'finalyp-580ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd39hN67PYt7C_G1pSWe4WkunAeE3wnw8',
    appId: '1:276263631177:ios:ae876792e44b7f5392c298',
    messagingSenderId: '276263631177',
    projectId: 'finalyp-580ad',
    storageBucket: 'finalyp-580ad.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd39hN67PYt7C_G1pSWe4WkunAeE3wnw8',
    appId: '1:276263631177:ios:ae876792e44b7f5392c298',
    messagingSenderId: '276263631177',
    projectId: 'finalyp-580ad',
    storageBucket: 'finalyp-580ad.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK3NQJxChbeKDzSlpfAIA2xaohgXjDTV4',
    appId: '1:276263631177:web:37296845eeb076b592c298',
    messagingSenderId: '276263631177',
    projectId: 'finalyp-580ad',
    authDomain: 'finalyp-580ad.firebaseapp.com',
    storageBucket: 'finalyp-580ad.firebasestorage.app',
    measurementId: 'G-Q6DVHP9ZSE',
  );
}
